/*
 * Accounts Write Data Plane
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.dpwallet.app.api.write.model;

import java.util.Objects;

import com.google.gson.annotations.SerializedName;

import io.swagger.annotations.ApiModelProperty;

/**
 * InlineObject
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2023-04-28T20:27:23.212681200-07:00[America/Los_Angeles]")
public class InlineObject {
  public static final String SERIALIZED_NAME_TXN_DATA = "txnData";
  @SerializedName(SERIALIZED_NAME_TXN_DATA)
  private String txnData;

  public InlineObject txnData(String txnData) {
    this.txnData = txnData;
    return this;
  }

   /**
   * Get txnData
   * @return txnData
  **/
  @ApiModelProperty(value = "")
  public String getTxnData() {
    return txnData;
  }

  public void setTxnData(String txnData) {
    this.txnData = txnData;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    InlineObject inlineObject = (InlineObject) o;
    return Objects.equals(this.txnData, inlineObject.txnData);
  }

  @Override
  public int hashCode() {
    return Objects.hash(txnData);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class InlineObject {\n");
    sb.append("    txnData: ").append(toIndentedString(txnData)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

