/*
 * Faucet Data Plane
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.dpwallet.app.api.faucet.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * FaucetTransactionSummaryResponse
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2023-07-04T23:26:29.859764400-07:00[America/Los_Angeles]")
public class FaucetTransactionSummaryResponse {
  public static final String SERIALIZED_NAME_ADDRESS = "address";
  @SerializedName(SERIALIZED_NAME_ADDRESS)
  private String address;

  public static final String SERIALIZED_NAME_FAUCET_COUNT = "faucetCount";
  @SerializedName(SERIALIZED_NAME_FAUCET_COUNT)
  private Object faucetCount = null;

  public static final String SERIALIZED_NAME_FAUCET_MAX_COUNT = "faucetMaxCount";
  @SerializedName(SERIALIZED_NAME_FAUCET_MAX_COUNT)
  private Object faucetMaxCount = null;

  public FaucetTransactionSummaryResponse address(String address) {
    this.address = address;
    return this;
  }

   /**
   * Get address
   * @return address
  **/
  @ApiModelProperty(value = "")
  public String getAddress() {
    return address;
  }

  public void setAddress(String address) {
    this.address = address;
  }

  public FaucetTransactionSummaryResponse faucetCount(Object faucetCount) {
    this.faucetCount = faucetCount;
    return this;
  }

   /**
   * Get faucetCount
   * @return faucetCount
  **/
  @ApiModelProperty(value = "")
  public Object getFaucetCount() {
    return faucetCount;
  }

  public void setFaucetCount(Object faucetCount) {
    this.faucetCount = faucetCount;
  }

  public FaucetTransactionSummaryResponse faucetMaxCount(Object faucetMaxCount) {
    this.faucetMaxCount = faucetMaxCount;
    return this;
  }

   /**
   * Get faucetMaxCount
   * @return faucetMaxCount
  **/
  @ApiModelProperty(value = "")
  public Object getFaucetMaxCount() {
    return faucetMaxCount;
  }

  public void setFaucetMaxCount(Object faucetMaxCount) {
    this.faucetMaxCount = faucetMaxCount;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    FaucetTransactionSummaryResponse faucetTransactionSummaryResponse = (FaucetTransactionSummaryResponse) o;
    return Objects.equals(this.address, faucetTransactionSummaryResponse.address) &&
        Objects.equals(this.faucetCount, faucetTransactionSummaryResponse.faucetCount) &&
        Objects.equals(this.faucetMaxCount, faucetTransactionSummaryResponse.faucetMaxCount);
  }

  @Override
  public int hashCode() {
    return Objects.hash(address, faucetCount, faucetMaxCount);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class FaucetTransactionSummaryResponse {\n");
    sb.append("    address: ").append(toIndentedString(address)).append("\n");
    sb.append("    faucetCount: ").append(toIndentedString(faucetCount)).append("\n");
    sb.append("    faucetMaxCount: ").append(toIndentedString(faucetMaxCount)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

