/*
 * Accounts Read Data Plane
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.dpwallet.app.api.read.model;

import java.util.Objects;

import com.google.gson.annotations.SerializedName;

import io.swagger.annotations.ApiModelProperty;

import java.util.ArrayList;
import java.util.List;

/**
 * AccountPendingTransactionSummaryResponse
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2023-04-28T20:27:13.465275500-07:00[America/Los_Angeles]")
public class AccountPendingTransactionSummaryResponse {
  public static final String SERIALIZED_NAME_PAGE_COUNT = "pageCount";
  @SerializedName(SERIALIZED_NAME_PAGE_COUNT)
  private Integer pageCount;

  public static final String SERIALIZED_NAME_RESULT = "result";
  @SerializedName(SERIALIZED_NAME_RESULT)
  private List<AccountPendingTransactionSummary> result = new ArrayList<AccountPendingTransactionSummary>();

  public AccountPendingTransactionSummaryResponse pageCount(Integer pageCount) {
    this.pageCount = pageCount;
    return this;
  }

   /**
   * Get pageCount
   * @return pageCount
  **/
  @ApiModelProperty(value = "")
  public Integer getPageCount() {
    return pageCount;
  }

  public void setPageCount(Integer pageCount) {
    this.pageCount = pageCount;
  }

  public AccountPendingTransactionSummaryResponse result(List<AccountPendingTransactionSummary> result) {
    this.result = result;
    return this;
  }

  public AccountPendingTransactionSummaryResponse addResultItem(AccountPendingTransactionSummary resultItem) {
    if (this.result == null) {
      this.result = new ArrayList<AccountPendingTransactionSummary>();
    }
    this.result.add(resultItem);
    return this;
  }

   /**
   * Get result
   * @return result
  **/
  @ApiModelProperty(value = "")
  public List<AccountPendingTransactionSummary> getResult() {
    return result;
  }

  public void setResult(List<AccountPendingTransactionSummary> result) {
    this.result = result;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AccountPendingTransactionSummaryResponse accountPendingTransactionSummaryResponse = (AccountPendingTransactionSummaryResponse) o;
    return Objects.equals(this.pageCount, accountPendingTransactionSummaryResponse.pageCount) &&
        Objects.equals(this.result, accountPendingTransactionSummaryResponse.result);
  }

  @Override
  public int hashCode() {
    return Objects.hash(pageCount, result);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AccountPendingTransactionSummaryResponse {\n");
    sb.append("    pageCount: ").append(toIndentedString(pageCount)).append("\n");
    sb.append("    result: ").append(toIndentedString(result)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

