name: Generated APK DP Wallet

env:
  # The name of the main module repository
  main_project_module: app

  # The name of the Play Store
  #playstore_name: dp wallet 

on:
  push:
    branches:
      - 'release/**'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
jobs:
  UnitTest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: make executable
        run: chmod +x gradlew
      - name: Unit tests
        run: |
          ./gradlew test
  BuildArtifacts:
    needs: UnitTest
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: make executable
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew build -x lint
      - name: Upload Debug
        uses: actions/upload-artifact@v2
        with:
          name: Debug Apk
          path: app/build/outputs/apk/debug/dp-wallet-debug.apk

  # https://dev.to/ychescale9/running-android-emulators-on-ci-from-bitrise-io-to-github-actions-3j76
  InstrumentedTests:
    needs: BuildArtifacts
    runs-on: macos-latest
    strategy:
      matrix:
        api-level: [21]
        arch: [x86_64]
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: Make gradlew executable
        run: chmod +x ./gradlew
      - name: run tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: ${{ matrix.api-level }}
          arch: ${{ matrix.arch }}
