name: Dp Wallet
env:
  main_project_module: app
on:
  push:
    tags:
    - '*'
jobs:
  BuildArtifacts:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: gradle
      - name: Install Dependencies
        run: |
           cd ${{ github.workspace }} 
           chmod +x install-android-library-ubuntu.sh 
           ./install-android-library-ubuntu.sh
      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew
      - name: Build with Gradle
        run: ./gradlew build
      - name: Build apk release project (APK) - ${{ env.main_project_module }} module
        run: ./gradlew assembleDebug --stacktrace
      - name: Upload DP Wallet APK Debug
        uses: actions/upload-artifact@v3
        with:
          name: dp-wallet-debug
          path: ${{ env.main_project_module }}/build/outputs/apk/debug/
  Release:
    name: Release Debug APK
    runs-on: ubuntu-latest
    needs: BuildArtifacts
    if: success() && startsWith(github.ref, 'refs/tags/v')
    steps:
      - name: Generate version string
        id: version-string
        run: echo "::set-output name=VERSION_STR::${GITHUB_REF##*/}"
 
      - name: Download all artifacts
        uses: actions/download-artifact@v3
 
      - name: Create a Debug APK
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          artifacts: "dp-wallet-debug/*.apk"
          name: Debug ${{ steps.version-string.outputs.VERSION_STR }}
          prerelease: ${{ contains(github.ref, '-alpha') || contains(github.ref, '-beta') }}
          tag: ${{ steps.version-string.outputs.VERSION_STR }}
          token: ${{ secrets.GITHUB_TOKEN }}
